config/routes.rb
Crowdfunder::Application.routes.draw do

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    resources :users
    resources :sessions

 
  resources :projects do
    resources :comments, :except => [:index]
    resources :pledges, :except => [:index]
  end

  root 'projects#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :pledges
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  after_save :backing_met_notification, if: :backing_met?

  attr_accessor :password, :password_confirmation

  has_many :projects
  has_many :pledges
  has_many :comments

  private
  def backing_met?
  	@project.pledges.sum(:amount) >= @project.goal
  end

  def backing_met_notification
  	UserMailer.backing_met(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  private
  def not_authenticated
  	redirect_to login_url, :alert => "First login to access this page"
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_filter :load_project


  def show
  	@comment = Comment.find(params[:id])
  end

  def create
  	# @comment = @project.comments.build(comment_params)
  	# @comment.user_id = user_id

    # instead of the above using the alternate sytax below
    @comment = Commnet.new(
      :remark => params[:comment][:remark],
      :project_id => @project_id,
      :user_id => current_user.id
      )
    if @comment.save
      redirect_to projects_path, notice: "Your comment has been added"
    else
      render :action => :show
    end   
  end

  def destroy
  	@review = Comment.find(params[:id])
  	@review.destroy
  end

  private
  	def comment_params
  		params.require(:comment).permit(:remark, :project_id)
	end

	def load_project
		@product = Product.find(paramns[:project_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_project
  

  def show
  	@comment = Comment.find(params[:id])
  end

  def create
  	# @comment = @project.comments.build(comment_params)
  	# @comment.user_id = user_id

    # instead of the above using the alternate sytax below
    @comment = Comment.new(
      :remark => params[:comment][:remark],
      :project_id => @project.id,
      :user_id => current_user.id
    )
    if @comment.save
      redirect_to projects_path, notice: "Your comment has been added"
    else
      render :action => :show
    end   
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy
  end

  private
  	def comment_params
  		params.require(:comment).permit(:remark, :project_id)
	end

	def load_project
		@project = Project.find(params[:project_id])
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_filter :load_project
  

  def show
  	@pledge = Pledge.find(params[:id])
  end

  def create
  	# @pledge = @project.pledges.build(pledge_params)
  	# @pledge.user_id = user_id

    # instead of the above using the alternate sytax below
    @pledge = Pledge.new(
      :amount => params[:pledge][:amount],
      :project_id => @project.id,
      :user_id => current_user.id
    )
    if @pledge.save
      redirect_to projects_path, notice: "Thank  you #{current_user.username} Your pledge has been added"
    else
      render :action => :show
    end   
  end

  def destroy
  	@pledge = Pledge.find(params[:id])
  	@pledge.destroy
  end

  private
  	def pledge_params
  		params.require(:pledge).permit(:amount, :project_id)
	end

	def load_project
		@project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, only:[:new, :create, :destroy] 

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    if current_user
      @comment = @project.comments.build
      @pledge = @project.pledges.build
    end
  end

  def destroy
    @project = Project.find(params[:id])

    if @project.user_id == current_user.id && @project.pledges.sum(:amount) ==0 &&  @project.end_date > Date.today
      @project.destroy
     redirect_to projects_url, :status => 301  
   else
     redirect_to projects_path
   end
  end

  def index
    @projects = Project.all
  end


  private
  def project_params

    params.require(:project).permit(:title, :description, :goal, :start_date, :end_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user=login(params[:email], params[:password])
		if user
			redirect_back_or_to root_url, :notice => "Logged in"
		else
			flash.now.alert ="Email or passowrd not correct"
			render :new
		end
	end

	def destroy
		logout
		redirect_to root_url, :notice => "Logged out"	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user =User.new
  end

  def create
  	@user=User.new(user_params)
  	if @user.save
  		redirect_to projects_path, :notice => "Signed up"
  	else
 		render :new
 	  end 			
  end

  def show
    @user = User.find(params[:id])    
  end


  private
  def user_params
  	params.require(:user).permit(:username,:email, :password, :password_confirmation, :bio)
  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/comment/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
	  Logged in as <%= current_user.email %>.
	  <%= link_to "Log out", logout_path %>
	<% else %>
	  <%= link_to "Sign up", signup_path %> or
	  <%= link_to "log in", login_path %>.
	<% end %>
<%= yield %>

</body>
</html>

app/views/pledges/create.html.erb
<h1>Pledges#create</h1>
<p>Find me in app/views/pledges/create.html.erb</p>

app/views/pledges/destroy.html.erb
<h1>Pledges#destroy</h1>
<p>Find me in app/views/pledges/destroy.html.erb</p>

app/views/pledges/show.html.erb
<h1>Pledges#show</h1>
<p>Find me in app/views/pledges/show.html.erb</p>

app/views/projects/index.html.erb
<h1>Available Projects</h1>

  <ul id="projects">
    <% @projects.each do |project| %>
      <li>
        <strong>Project Owner: <%= link_to "#{project.user.username}",user_path(project.user.id) %><%=  %></strong><br/>
        <strong>Project Title: <%= project.title %></strong><br />
         <strong>Project Overview: </strong><%= project.description %>. <br /> 
        <strong>Goal: </strong><%= project.goal %><br />
        <strong>Start date: </strong><%= project.start_date %><br />
        <strong>End date: </strong><%= project.end_date %><br/>
          <strong>Project id:</strong> <%= project.id %><br/>
          <%= link_to "View Project", project_path(project) %>
      </li><br>
    <% end %>
  </ul>


  <!-- for req. #7 we should use javascript to display pledge amount input field if user click <Click to back this project> button -->
  <!-- similar approach may be the way to go for several requirements -->

  <%= link_to ">> Create New Project", new_project_path, class: "new_project" %>
  

app/views/projects/new.html.erb
<h1>Create Your Project</h1>

<%= form_for @project do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :goal %><br />
    <%= f.number_field :goal %>
  </div>

  <!-- Need to figure out date pickers for start_data and end_date Note as of: Dec 3 -->
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>


  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>



   <div class="field">
      <%= f.submit %>
  </div>

<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %> </h1>
<h3>by: <%= @project.user.username %></h3>
<p>Description: <%= @project.description %></p>
<p>Goal Amount: $<%= @project.goal %></p>
<p>Start Date: <%= @project.start_date %></p>
<p>End Date: <%= @project.end_date %></p>
<p>Total amount funded to date: $<%= @project.pledges.sum(:amount) %> </p>
<p>Funding Status: <%= ((@project.pledges.sum(:amount)/@project.goal).to_f)*100 %> %</p>

<% if current_user %>
	

	<h3>Comments</h3>
	<!-- <p>Comments for <%= @project.title %></p> -->
	<% @project.comments.each do |c| %> 
		<p>
		<% if c.user != nil %>
			<em> by <%= c.user.username %></em>
			<strong><%= c.remark %></strong>
			Added on: <%= c.created_at %> 
		<% end %>
		</p>
	<% end %> 

	<h4>New Comment</h4>
	<%= form_for([@project, @comment]) do |f| %> 
		<% if @comment.errors.any? %>
			<div id="error_explanation">
			<h2><%= pluralize(@comment.errors.count, "error") %> prohibited this review from being saved:</h2>
			<ul>
			<% @comment.errors.full_messages.each do |msg| %> 
				<li><%= msg %></li>
			<% end %>
			</ul> 
			</div>
		<% end %>
		<div class="field">
		<%= f.label :comment %><br /> <%= f.text_area :remark %>
		</div>
		<div class="actions">
		<%= f.submit %> 
		</div>
	<% end %>
	<h4>Back this project</h4>
	<%= form_for([@project, @pledge]) do |f| %>
		  <div class="field">
    		<%= f.label :Enter_Pledge_amount_Dollars %><br />
    		<%= f.number_field :amount %>
  		</div>
  		 <div class="field">
      		<%= f.submit "Submit my pledge" %>
  		</div>
	<% end %>

<% else %>
	<p>Please <%= link_to "log in", new_session_path %> to add a review or make a pledge.</p>
<% end %>






<%= link_to ">> Back to Projects List", projects_path %><br />
<%= link_to ">> Delete Project", @project, method: :delete, data:{ confirm: "Are you sure you want to delete this project?"} %>

app/views/users/new.html.erb
<h1>Create your account</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1>Hello : <em><%= @user.username %></em> </h1>

<p>About : <%= @user.bio %></p>
<h2>Projects Created : </h2>
<% if @user.projects.size >0 %>
	<% @user.projects.each do |project| %>
	      <li>
	        <strong>Project Title: </strong><%= project.title %><br />
	         <strong>Project Overview: </strong><%= project.description %>. <br /> 
	        <strong>Goal: </strong><%= project.goal %><br />
	        <strong>Start date: </strong><%= project.start_date %><br />
	        <strong>End date: </strong><%= project.end_date %><br/>
			<strong>Total amount funded to date: </strong>$ <%= project.pledges.sum(:amount) %> <br/>
			<strong>Funding Status: </strong><%= ((project.pledges.sum(:amount)/project.goal).to_f)*100 %> %</br>
	         <strong>Project id:</strong> <%= project.id %><br/>
	         <%= link_to "View Project", project_path(project) %>
	      </li><br>
	    <% end %>
<% else %>
	<h3>You have not created any projects - Do something ---add a project--- make the world a better place</h3>
<% end %>

<h2>Projects Backed : </h2>
<% if @user.pledges.size >0 %>
	<% @user.projects.each do |project| %>
	      <li>
	        <strong>Project Title: </strong><%= project.title %><br />
	         <strong>Project Overview: </strong><%= project.description %>. <br /> 
	        <strong>Goal: </strong><%= project.goal %><br />
	        <strong>Start date: </strong><%= project.start_date %><br />
	        <strong>End date: </strong><%= project.end_date %><br/>
			<strong>Total amount funded to date: </strong>$ <%= project.pledges.sum(:amount) %> <br/>
			<strong>Funding Status: </strong><%= ((project.pledges.sum(:amount)/project.goal).to_f)*100 %> %</br>
	         <strong>Project id:</strong> <%= project.id %><br/>
	         <%= link_to "View Project", project_path(project) %>
	      </li><br>
	<% end %>
<% else %>
	<em><h4>You have not backed any projects - Do something ---spend some money --back a project--- make the world a better place</h4></em>
<% end %>
 


 






  <%= link_to ">> Back to Projects List", projects_path %><br />